Update maven.yml

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -1,8 +1,9 @@
-name: Test Automation Workflow
+
+   name: Test Automation Workflow
 
 on:
   schedule:
-  - cron: 00 18 * * *
+    - cron: '00 18 * * *'
   push:
     branches: [ "master" ]
   pull_request:
@@ -10,41 +11,49 @@ on:
 
 jobs:
   build:
-
     runs-on: ubuntu-latest
 
     steps:
     - uses: actions/checkout@v4
+
     - name: Set up JDK 11
       uses: actions/setup-java@v4
       with:
         java-version: '11'
         distribution: 'temurin'
         cache: maven
-    - name: Running Test Automation Framework with Maven
-      run: mvn test -X -Dbrowser=chrome -DisLambdaTest=true -DisHeadLess=false
 
+    - name: Debug - Check login data file
+      run: |
+        echo "PWD: $(pwd)"
+        find . -name loginData.json || echo "File not found!"
+
+    - name: Run Tests with Maven and LambdaTest
+      env:
+        LT_USERNAME: ${{ secrets.kunrajpurohit1 }}
+        LT_ACCESS_KEY: ${{ secrets.LT_PZu0aZMuOClZAYAqBGyA3kKaPL3UpJx4BtBtrkN7GRh39Vh }}
+      run: mvn test -X -Dbrowser=chrome -DisLambdaTest=true -DisHeadLess=false
 
     - name: Upload Test logs
       if: always()
-      uses: actions/upload-artifact@v4.6.2
+      uses: actions/upload-artifact@v4
       with:
-       name: Test logs
-       path: logs/
+        name: Test logs
+        path: logs/
 
     - name: Upload Screenshots as Artifacts
       if: always()
-      uses: actions/upload-artifact@v4.6.2
+      uses: actions/upload-artifact@v4
       with:
-       name: screenshots
-       path: screenshots/
+        name: screenshots
+        path: screenshots/
 
     - name: Upload HTML Report as Artifacts
       if: always()
-      uses: actions/upload-artifact@v4.6.2
+      uses: actions/upload-artifact@v4
       with:
-       name: html-report
-       path: report.html
+        name: html-report
+        path: report.html
 
     - name: Test Execution Status
       if: always()
@@ -52,20 +61,20 @@ jobs:
 
     - name: Copy report to gh-pages Folder
       if: always()
-
       run: |
         mkdir -p public/extent-reports
         cp -R report.html public/extent-reports/
         cp -R screenshots/ public/extent-reports/screenshots/
-        ls -l
+        ls -l public/extent-reports
 
     - name: Deploy
       if: always()
       uses: JamesIves/github-pages-deploy-action@v4
       with:
-       folder: public/extent-reports/
-       token: $({ secrets.PAT })
-       clean: true
+        folder: public/extent-reports/
+        token: ${{ secrets.PAT }}
+        clean: true
+
 
 
 
